### ISSUE TITLE
prompts are always possibly undefined 

### ISSUE THREAD

**Issue by tigawanna** [fabiospampinato/prask#1] opened 2023-08-16 12:03 UTC
Hey there,  been enjoying your great package, but have had 2 issues.
1. I noticed the prompt output will still be possibly undefined even if an initial value is passed in 
2. The boolean field is returning an array with a single boolean, not a boolean or undefined
3. I tried setting up the project locally to try fixing it but it's not behaving as expected, the dev version is behaving synchronously 
calling this snippet
```ts
import { boolean } from "prask";

async function test() {
  try {
    const value = await boolean({ message: "test this", initial: false });
    if (value) {
      console.log("value defined", value);
    } else {
      console.log("value undefined");
    }
    return value;
  } catch (e) {
    console.log(e);
  }
}

test()
  // .then(res=>console.log("response",res))
  .catch(console.error);
``` 
 locally built version
```tsx
PS C:\Users\denni\Desktop\code\vite\vite-bonita-test> tsx src\run.ts
? test this
❯ No
  Yasvalue undefined
```
the ppm version
```sh
PS C:\Users\denni\Desktop\code\vite\vite-bonita-test> tsx src\run.ts
✔ test this Yes
value defined [ true ]
```

I've tried all the compile commands
```json
{
   "compile": "tsex compile",
    "compile:watch": "tsex compile --watch",
    "prepublishOnly": "tsex prepare"
}
```
 any help?

**Comment by fabiospampinato** [comment] 2023-08-16 13:16
> I noticed the prompt output will still be possibly undefined even if an initial value is passed in

Yeah that's by design, to allow the user to always sort of "close" the prompt. I'm not sure it's the right decision, but that's how it works for now.

> The boolean field is returning an array with a single boolean, not a boolean or undefined

Just fixed it in v1.5.2, thank you!

> I tried setting up the project locally to try fixing it but it's not behaving as expected, the dev version is behaving synchronously

Can you post a screenshot of this?

```
PS C:\Users\denni\Desktop\code\vite\vite-bonita-test> tsx src\run.ts
? test this
❯ No
  Yasvalue undefined
```

Did you change the library to output "Yas" rather than "Yes"?

**Comment by tigawanna** [comment] 2023-08-16 13:35
Yes I changed it to Yas to confirm that it was building , peeked in the code and it seems like returning the initial value and only being possibly undefined if no initial value is set might not be as simple. 
Thanks for the great work

**Comment by fabiospampinato** [comment] 2023-08-16 13:41
> returning the initial value and only being possibly undefined if no initial value is set might not be as simple.

You could write code like this for that:

```ts
const result = await string ({ 
  message: 'Some question',
  initial: 'Some value' 
}) ?? 'Some value';
```

Closing as it sounds like the problem was solved, but let me know if you find any other bugs 👍

**Closed as completed by fabiospampinato** 2023-08-16 13:41 UTC
